import subprocess
from openai import OpenAI
from print_color import print


def debug_code(test_file: str, code_file: str, problem_description: str,
               client: OpenAI, model: str,
               n_retries: int = 3):
    try:
        command_output = subprocess.check_output(f"poetry run pytest {test_file}",
                                                 shell=True, stderr=subprocess.STDOUT)
        print(command_output)
    except subprocess.CalledProcessError as error:
        error_message = error.output.decode("utf-8")
        print(error_message, color="red")
        if n_retries == 0:
            raise Exception("Unable to make the tests pass")

        with open(test_file, "r") as f:
            tests = f.read()

        with open(code_file, "r") as f:
            code = f.read()

        prompt = f"""
You are a skilled programmer. You can fix the code generated by the AI.

The AI tries to solve the following problem using TDD: {problem_description}.

Here are the current tests :
    
```python
{tests}
```

The AI generated the following code : 

```python
{code}
```

However, the tests failed with the following error message :
{error_message}
    
Please fix the code in order for it to pass the tests.
Please first describe how you should update the code, then generate the fixed code.
You should output the whole file including the imports, and in no case output the tests themselves.
"""
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            model=model,
        )
        output = chat_completion.choices[0].message.content
        if "```python" in output:
            new_code = output.split("```python")[-1].split("```")[0]
            print(new_code, "blue")
            with open(code_file, "w") as f:
                f.write(new_code)
        debug_code(test_file, code_file, problem_description, client, model, n_retries - 1)




